---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-worker
spec:
  replicas: 2 # Adjust based on needed compute resources
  selector:
    matchLabels:
      app: dask-worker
  template:
    metadata:
      labels:
        app: dask-worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoreDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                operator: In
                values:
                  - dask-worker
      containers:
      - name: dask-worker
        image: docker.io/pebcac/dask-worker:0.1
